# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_cards',
                'doc_host': 'https://Sophie-Flack.github.io',
                'git_url': 'https://github.com/Sophie-Flack/nbdev_cards',
                'lib_path': 'nbdev_cards'},
  'syms': {'nbdev_cards.core': {'nbdev_cards.core.foo': ('core.html#foo', 'nbdev_cards/core.py')}}}
